### ISSUE TITLE
Unipolar IRT and the Author Recognition Test (ART)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#134] opened 2024-08-28 12:44 UTC
We have data from other author recognition tests so need to double check which of their data may be duplicative.
https://link.springer.com/article/10.3758/s13428-023-02275-2

**Comment by KingArthur0205** [comment] 2024-08-30 14:12
Working on this

**Comment by KingArthur0205** [comment] 2024-08-30 15:03
Dataset 1. Just in case the data is missing, I have re-run the code and generated the data.
[art.csv](https://github.com/user-attachments/files/16818857/art.csv)

**Comment by KingArthur0205** [comment] 2024-08-30 15:39
For the 2nd dataset, the columns are in Dutch instead of English. Do we have to switch the langue of columns into English? 

The columns include questionnaries **items**(Is de volgende persoon een auteur- [Simone van der Vlugt]) and **features of participants**(age, mother language, and etc.). My current thought is to switch participants' features into English and leave the artists' names as items rather than the entier question.

Is de volgende persoon een auteur- [Simone van der Vlugt]: Is the following person an author- [Simone van der Vlugt]

**Comment by ben-domingue** [comment] 2024-08-30 16:05
McCarron & Kuperman: I have these in my 'to be posted' queue. Good catch. They are not clearly licensed so I have an outstanding email to the authors. 

Brysbaert: I want to make sure I follow. I'm ok with translating respondent features but I would not translate the items. Is that consistent with your plan?

**Comment by KingArthur0205** [comment] 2024-08-30 16:08
> McCarron & Kuperman: I have these in my 'to be posted' queue. Good catch. They are not clearly licensed so I have an outstanding email to the authors. 
> 
> 
> 
> Brysbaert: I want to make sure I follow. I'm ok with translating respondent features but I would not translate the items. Is that consistent with your plan? 

Brysbaert: Yes, this sounds great and also saves efforts. :)

**Comment by ben-domingue** [comment] 2024-08-30 16:09
i'm going to sen an email with a little context about the translation issue.

**Comment by KingArthur0205** [comment] 2024-08-31 06:43
Brysbaert:
This paper contains 5 studies and 4 datasets. However, the provided datasets do not correspond to the 5 studies. 
1. **Study 1**: This study focused on memory/recognition for texts in Dutch or English. The data for this study was not provided. However, participants in the recognition experiment also completed the **Dutch Artist Recognition Test (DART)**, for which item-level response data is available.
_Note: The memory/recognition experiment involved 195 participants, while Dataset 1 contains data for 200 participants, 5 of whom are non-native Dutch speakers. It is assumed that the 195 native Dutch speakers participated in the memory/recognition study._
2. **Study 2**: This study examined whether introverts read more books than extroverts. Dataset 1 includes the number of books each participant read in the past year, but lacks data indicating whether the participants are introverts or extroverts. Due to this data incompleteness, this study is excluded.
3. **Study 3**: DART data provided for 85 participants, consistent with paper.
4. **Study 4**: DART data provided for 72 students, consistent with paper
5. **Study 5**: DART data provided for 62 participants, designed with using younger artists as items. Consistent with paper.

**Comment by KingArthur0205** [comment] 2024-08-31 13:34
For the 3rd dataset **Grolig**:
This paper presents two datasets derived from studies on German ART conducted on different occasions. The first dataset was gathered during a consented study, while the second was collected from participants taking a quiz at a book fair.

However, there are some inconsistencies between the dataset and the details reported in the paper.

1. **Dataset 1**: The paper reports that 108 participants took part in the study. However, the OSF dataset contains 120 participants, with 5 of them not disclosing their gender. Excluding these participants reduces the count to 116.
2. **Dataset 2**: According to the paper, 252 participants took the quiz, with 21 excluded due to missing age data or because they were not adolescents, leaving 231 valid participants. Yet, the OSF dataset only contains 223 entries.

When summing 116 from the first dataset and 223 from the second, the total aligns with the number of participants stated in the paper. I wanted to highlight this inconsistency for your awareness.

**Comment by ben-domingue** [comment] 2024-09-02 20:30
a few notes about this. 
- i probably made too big of a point about getting the sample sizes to match in that one case. that isn't so pressing in general; i think i got focused on it there and it seemed easy to fix as you had the answer. in general, i make sure sample sizes are comparable between what is in data and what they report just as a means of sanity checking but a 1-2% differences in the sample sizes don't matter. 
-when the same measure is given to multiple populations, we can collapse those into one dataset. i *do not* want to collapse multiple measures in the same population to one dataset, but it's fine to have different samples taking the same measure all in one place so long as the item IDs are consistent. we can always add a column flagging the different populations as well. 

does that help clarify some things for this study and in general?

**Comment by KingArthur0205** [comment] 2024-09-03 00:32
> a few notes about this.
> 
> * i probably made too big of a point about getting the sample sizes to match in that one case. that isn't so pressing in general; i think i got focused on it there and it seemed easy to fix as you had the answer. in general, i make sure sample sizes are comparable between what is in data and what they report just as a means of sanity checking but a 1-2% differences in the sample sizes don't matter.
>   -when the same measure is given to multiple populations, we can collapse those into one dataset. i _do not_ want to collapse multiple measures in the same population to one dataset, but it's fine to have different samples taking the same measure all in one place so long as the item IDs are consistent. we can always add a column flagging the different populations as well.
> 
> does that help clarify some things for this study and in general?

Thank you! This is very informative, and I believe it would be a valuable addition to the standard. Perhaps we could include it in a FAQ section. :)

In the future, I’ll ensure to double-check population numbers and flag any significant inconsistencies if they arise.

**Comment by KingArthur0205** [comment] 2024-09-03 11:40
**Second Dataset: Brysbaert**

The second and third studies utilized the same questionnaire, with the same set of authors as items. The key difference between the studies is the population, with the 3rd study focusing on less educated young people. Therefore, it may be appropriate to **merge these two datasets into one**. I will add a label to indicate the origin of each data set.

**Third Dataset: Grolig**

The two datasets were collected using different questionnaires, each with a distinct set of authors as items. Consequently, it would be advisable to keep these two datasets separate.

**Comment by ben-domingue** [comment] 2024-09-03 12:38
> Thank you! This is very informative, and I believe it would be a valuable addition to the standard. Perhaps we could include it in a FAQ section. :)

Just added [here](https://github.com/datapages/irw/tree/data-standard). Good point!

And your analysis of the datasets I think is mostly right. For Grolig, I do have one question:

> each with a distinct set of authors as items.

Was there any overlap between the sets? If so, I think we should actually put them together (you can do various scaling tricks to put things on the same scale if there is some subset of common authors between the two).

**Comment by KingArthur0205** [comment] 2024-09-03 12:50
> Was there any overlap between the sets? If so, I think we should actually put them together (you can do various scaling tricks to put things on the same scale if there is some subset of common authors between the two).

Yes, I believe there may be some overlaps. I’ll double-check and get back to you shortly. If confirmed, the second Brysbaert study shares some common author items across all four datasets. In that case, should we consider combining them?

Regarding the scale, I think the responses were all given as True/False, so the merging process should be straightforward.

Thank you for clarifying!



> Just added [here](https://github.com/datapages/irw/tree/data-standard). Good point!
I’m also working on summarizing our conversations into an FAQ document and should have it ready later today. There might be insights we've discussed that could be helpful to others as well. I’ll share it with you once it’s done. ：）
 ：）

**Comment by ben-domingue** [comment] 2024-09-03 13:01
yeah if there are common authors i'd put them together!

**Comment by KingArthur0205** [comment] 2024-09-03 13:08
> yeah if there are common authors i'd put them together!

Okay, I'll make the changes right now. Should we add a column to indicate the different groups they came from? Currently, I'm labeling them as "Study 1, ...4" to reflect their different origins.

**Comment by ben-domingue** [comment] 2024-09-03 13:10
study 1...4: perfect!

**Comment by KingArthur0205** [comment] 2024-09-03 13:38
Refinement completed. The first dataset from Grolig cannot be merged with the others due to having different item naming formats.

I also manually checked the participant IDs, and there don't appear to be any conflicts, so it should be safe to merge the remaining datasets.

**Comment by ben-domingue** [comment] 2024-09-03 19:19
ok, this one has been a journey. apologies! 
two questions:
- can you clarify which of the above datasets i should add? i'm not sure which are new and which are outdated? maybe even just repost them? 
- i don' think there is an associated pull request for this one yet?

**Comment by KingArthur0205** [comment] 2024-09-04 05:08
> ok, this one has been a journey. apologies! two questions:

It’s been a fun journey, and I really appreciate how seriously and rigorously we’re treating these data!

> * can you clarify which of the above datasets i should add? i'm not sure which are new and which are outdated? maybe even just repost them?

I’ve been updating the datasets above on the go, and they should now all be up-to-date. For our convenience, I’ve also attached them here:
**DART 2020**
[DART_Brysbaert_2020_3&4&5.csv](https://github.com/user-attachments/files/16861091/DART_Brysbaert_2020_3.4.5.csv)
[DART_Brysbaert_2020_1.csv](https://github.com/user-attachments/files/16861073/DART_Brysbaert_2020_1.csv)
**GART 2020**
[GART_Grolig_2020.csv](https://github.com/user-attachments/files/16861078/GART_Grolig_2020.csv)


> * i don' think there is an associated pull request for this one yet?

Just created. Wanted to make sure that data is fully ready before posting anything👍  : https://github.com/ben-domingue/irw/pull/161

**Closed** 2024-09-04 13:53 UTC
Labels: data queue
